/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Status da API e de cada dependência externa.
     */
    get: operations['health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Entra com empresa (slug), e-mail e senha. O refresh token vai em cookie HttpOnly.
     */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh
     * @description Troca o refresh token (cookie) por um novo par de tokens (rotação).
     */
    post: operations['refresh_api_v1_auth_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_v1_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Users */
    get: operations['list_users_api_v1_users_get']
    put?: never
    /** Create User */
    post: operations['create_user_api_v1_users_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update User */
    patch: operations['update_user_api_v1_users__user_id__patch']
    trace?: never
  }
  '/api/v1/suppliers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Buscar
     * @description Busca por similaridade de nome (tolerante a acentos e erros de digitação) ou CNPJ.
     */
    get: operations['buscar_api_v1_suppliers_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_suppliers_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/suppliers/{supplier_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obter */
    get: operations['obter_api_v1_suppliers__supplier_id__get']
    put?: never
    post?: never
    /** Excluir */
    delete: operations['excluir_api_v1_suppliers__supplier_id__delete']
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_suppliers__supplier_id__patch']
    trace?: never
  }
  '/api/v1/categorias': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar */
    get: operations['listar_api_v1_categorias_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_categorias_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categorias/{obj_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_categorias__obj_id__patch']
    trace?: never
  }
  '/api/v1/projetos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar */
    get: operations['listar_api_v1_projetos_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_projetos_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projetos/{obj_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_projetos__obj_id__patch']
    trace?: never
  }
  '/api/v1/centros-custo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar */
    get: operations['listar_api_v1_centros_custo_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_centros_custo_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/centros-custo/{obj_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_centros_custo__obj_id__patch']
    trace?: never
  }
  '/api/v1/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar */
    get: operations['listar_api_v1_tags_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_tags_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tags/{obj_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_tags__obj_id__patch']
    trace?: never
  }
  '/api/v1/lancamentos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Listar
     * @description Lista ordenada por vencimento (mais próximo primeiro; sem vencimento no fim).
     */
    get: operations['listar_api_v1_lancamentos_get']
    put?: never
    /** Criar */
    post: operations['criar_api_v1_lancamentos_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/lancamentos/{lanc_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obter */
    get: operations['obter_api_v1_lancamentos__lanc_id__get']
    put?: never
    post?: never
    /** Excluir */
    delete: operations['excluir_api_v1_lancamentos__lanc_id__delete']
    options?: never
    head?: never
    /** Atualizar */
    patch: operations['atualizar_api_v1_lancamentos__lanc_id__patch']
    trace?: never
  }
  '/api/v1/uploads/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Criar Lote
     * @description Cria o lote e devolve uma URL de upload por arquivo (PUT direto no storage).
     *
     *     A URL fixa tipo e tamanho declarados: um arquivo diferente é recusado pelo storage.
     */
    post: operations['criar_lote_api_v1_uploads_batch_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/uploads/{comprovante_id}/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirmar
     * @description Confirma o envio e dispara a validação em segundo plano. Idempotente.
     */
    post: operations['confirmar_api_v1_uploads__comprovante_id__complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/uploads/{comprovante_id}/retry-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Nova Url
     * @description Nova URL para reenviar um arquivo cujo upload falhou ou expirou.
     */
    post: operations['nova_url_api_v1_uploads__comprovante_id__retry_url_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/uploads/batch/{batch_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Status Lote
     * @description Status item a item + agregados. Pensado para polling (servido do cache).
     */
    get: operations['status_lote_api_v1_uploads_batch__batch_id__status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/comprovantes/{comprovante_id}/arquivo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Baixar Arquivo
     * @description Redireciona para o original (link temporário, sempre como download).
     */
    get: operations['baixar_arquivo_api_v1_comprovantes__comprovante_id__arquivo_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/comprovantes/{comprovante_id}/thumbnail': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Miniatura */
    get: operations['miniatura_api_v1_comprovantes__comprovante_id__thumbnail_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ArquivoDeclarado */
    ArquivoDeclarado: {
      /**
       * Nome
       * @example boleto_luz.pdf
       */
      nome: string
      /**
       * Tamanho Bytes
       * @example 184320
       */
      tamanho_bytes: number
      /**
       * Mime Type
       * @description Informativo: o tipo real é detectado pelo servidor
       */
      mime_type?: string | null
    }
    /** CategoriaIn */
    CategoriaIn: {
      /** Nome */
      nome: string
    }
    /** CategoriaOut */
    CategoriaOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Ativo */
      ativo: boolean
    }
    /** CategoriaUpdate */
    CategoriaUpdate: {
      /** Nome */
      nome?: string | null
      /** Ativo */
      ativo?: boolean | null
    }
    /** CentroCustoIn */
    CentroCustoIn: {
      /** Codigo */
      codigo: string
      /** Nome */
      nome: string
    }
    /** CentroCustoOut */
    CentroCustoOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Codigo */
      codigo: string
      /** Nome */
      nome: string
      /** Ativo */
      ativo: boolean
    }
    /** CentroCustoRef */
    CentroCustoRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Codigo */
      codigo: string
    }
    /** CentroCustoUpdate */
    CentroCustoUpdate: {
      /** Codigo */
      codigo?: string | null
      /** Nome */
      nome?: string | null
      /** Ativo */
      ativo?: boolean | null
    }
    /** ComponentHealth */
    ComponentHealth: {
      status: components['schemas']['Status']
      /** Latency Ms */
      latency_ms?: number | null
      /** Detail */
      detail?: string | null
    }
    /** Confirmacao */
    Confirmacao: {
      /**
       * Status
       * @enum {string}
       */
      status:
        'enviando' | 'validando' | 'processando_ocr' | 'aguardando_revisao' | 'concluido' | 'erro'
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthReport */
    HealthReport: {
      status: components['schemas']['Status']
      /** Environment */
      environment: string
      /** Components */
      components: {
        [key: string]: components['schemas']['ComponentHealth']
      }
    }
    /** ItemStatus */
    ItemStatus: {
      /**
       * Comprovante Id
       * Format: uuid
       */
      comprovante_id: string
      /** Nome */
      nome: string
      /** Tamanho Bytes */
      tamanho_bytes: number
      /** Mime Type */
      mime_type: string
      /**
       * Status
       * @enum {string}
       */
      status:
        'enviando' | 'validando' | 'processando_ocr' | 'aguardando_revisao' | 'concluido' | 'erro'
      /** Erro Msg */
      erro_msg: string | null
      /** Total Paginas */
      total_paginas: number
      /** Possivel Duplicado */
      possivel_duplicado: boolean
      /** Tem Miniatura */
      tem_miniatura: boolean
    }
    /** LancamentoIn */
    LancamentoIn: {
      /**
       * Valor
       * @example 245.90
       */
      valor: number | string
      /**
       * Data Emissao
       * Format: date
       */
      data_emissao: string
      /** Data Pagamento Prevista */
      data_pagamento_prevista?: string | null
      /** Supplier Id */
      supplier_id?: string | null
      /** Categoria Id */
      categoria_id?: string | null
      /** Projeto Id */
      projeto_id?: string | null
      /** Centro Custo Id */
      centro_custo_id?: string | null
      /** Descricao */
      descricao?: string | null
      /** Forma Pagamento */
      forma_pagamento?:
        ('boleto' | 'pix' | 'cartao' | 'dinheiro' | 'transferencia' | 'outro') | null
      /** Linha Digitavel */
      linha_digitavel?: string | null
      /** Tag Ids */
      tag_ids?: string[]
    }
    /** LancamentoOut */
    LancamentoOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Valor */
      valor: string
      /**
       * Data Emissao
       * Format: date
       */
      data_emissao: string
      /** Data Pagamento Prevista */
      data_pagamento_prevista: string | null
      /** Data Pagamento Efetiva */
      data_pagamento_efetiva: string | null
      supplier: components['schemas']['SupplierRef'] | null
      categoria: components['schemas']['Ref'] | null
      projeto: components['schemas']['Ref'] | null
      centro_custo: components['schemas']['CentroCustoRef'] | null
      /** Tags */
      tags: components['schemas']['Ref'][]
      usuario: components['schemas']['Ref']
      /** Descricao */
      descricao: string | null
      /** Forma Pagamento */
      forma_pagamento: ('boleto' | 'pix' | 'cartao' | 'dinheiro' | 'transferencia' | 'outro') | null
      /** Linha Digitavel */
      linha_digitavel: string | null
      /** Status */
      status: string
      status_efetivo: components['schemas']['StatusEfetivo']
      /** Dias Para Vencimento */
      dias_para_vencimento: number | null
      /** Status Aprovacao */
      status_aprovacao: string
      /** Version */
      version: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** LancamentoPage */
    LancamentoPage: {
      /** Items */
      items: components['schemas']['LancamentoOut'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /**
     * LancamentoUpdate
     * @description Atualização parcial: só os campos enviados são alterados (null limpa o campo).
     */
    LancamentoUpdate: {
      /** Valor */
      valor?: (number | string) | null
      /** Data Emissao */
      data_emissao?: string | null
      /** Data Pagamento Prevista */
      data_pagamento_prevista?: string | null
      /** Supplier Id */
      supplier_id?: string | null
      /** Categoria Id */
      categoria_id?: string | null
      /** Projeto Id */
      projeto_id?: string | null
      /** Centro Custo Id */
      centro_custo_id?: string | null
      /** Descricao */
      descricao?: string | null
      /** Forma Pagamento */
      forma_pagamento?:
        ('boleto' | 'pix' | 'cartao' | 'dinheiro' | 'transferencia' | 'outro') | null
      /** Linha Digitavel */
      linha_digitavel?: string | null
      /** Tag Ids */
      tag_ids?: string[] | null
    }
    /** LoginRequest */
    LoginRequest: {
      /**
       * Tenant Slug
       * @example acme
       */
      tenant_slug: string
      /**
       * Email
       * @example colaborador@acme.com.br
       */
      email: string
      /** Senha */
      senha: string
    }
    /** LoteCriado */
    LoteCriado: {
      /**
       * Batch Id
       * Format: uuid
       */
      batch_id: string
      /**
       * Expira Em
       * Format: date-time
       */
      expira_em: string
      /** Itens */
      itens: components['schemas']['UploadInstrucao'][]
    }
    /** LoteStatus */
    LoteStatus: {
      /**
       * Batch Id
       * Format: uuid
       */
      batch_id: string
      /** Total */
      total: number
      /** Concluidos */
      concluidos: number
      /** Com Erro */
      com_erro: number
      /** Em Andamento */
      em_andamento: number
      /** Itens */
      itens: components['schemas']['ItemStatus'][]
    }
    /** Me */
    Me: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Email */
      email: string
      /**
       * Role
       * @enum {string}
       */
      role: 'admin' | 'aprovador' | 'colaborador'
      /** Nivel Aprovacao */
      nivel_aprovacao: number
      tenant: components['schemas']['TenantInfo']
    }
    /** NovoLote */
    NovoLote: {
      /** Arquivos */
      arquivos: components['schemas']['ArquivoDeclarado'][]
      /**
       * Origem
       * @default web
       * @enum {string}
       */
      origem: 'web' | 'mobile'
    }
    /** ProjetoIn */
    ProjetoIn: {
      /** Nome */
      nome: string
    }
    /** ProjetoOut */
    ProjetoOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Ativo */
      ativo: boolean
    }
    /** ProjetoUpdate */
    ProjetoUpdate: {
      /** Nome */
      nome?: string | null
      /** Ativo */
      ativo?: boolean | null
    }
    /** Ref */
    Ref: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
    }
    /**
     * Status
     * @enum {string}
     */
    Status: 'ok' | 'error'
    /**
     * StatusEfetivo
     * @enum {string}
     */
    StatusEfetivo: 'pendente' | 'reagendado' | 'vence_hoje' | 'atrasado' | 'pago' | 'rejeitado'
    /** SupplierIn */
    SupplierIn: {
      /** Nome Fantasia */
      nome_fantasia: string
      /** Razao Social */
      razao_social?: string | null
      /**
       * Cnpj
       * @example 11.222.333/0001-81
       * @example 12.ABC.345/01DE-35
       */
      cnpj?: string | null
    }
    /** SupplierOut */
    SupplierOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome Fantasia */
      nome_fantasia: string
      /** Razao Social */
      razao_social: string | null
      /** Cnpj */
      cnpj: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Cnpj Formatado */
      readonly cnpj_formatado: string | null
    }
    /** SupplierRef */
    SupplierRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome Fantasia */
      nome_fantasia: string
      /** Cnpj */
      cnpj: string | null
    }
    /** SupplierUpdate */
    SupplierUpdate: {
      /** Nome Fantasia */
      nome_fantasia?: string | null
      /** Razao Social */
      razao_social?: string | null
      /** Cnpj */
      cnpj?: string | null
    }
    /** TagIn */
    TagIn: {
      /** Nome */
      nome: string
    }
    /** TagOut */
    TagOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Ativo */
      ativo: boolean
    }
    /** TagUpdate */
    TagUpdate: {
      /** Nome */
      nome?: string | null
      /** Ativo */
      ativo?: boolean | null
    }
    /** TenantInfo */
    TenantInfo: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Slug */
      slug: string
    }
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type: 'bearer'
      /** Expires In */
      expires_in: number
      user: components['schemas']['Me']
    }
    /** UploadInstrucao */
    UploadInstrucao: {
      /**
       * Comprovante Id
       * Format: uuid
       */
      comprovante_id: string
      /** Nome */
      nome: string
      /** Upload Url */
      upload_url: string
      /** Headers */
      headers: {
        [key: string]: string
      }
    }
    /** UserCreate */
    UserCreate: {
      /** Nome */
      nome: string
      /**
       * Email
       * Format: email
       */
      email: string
      /** Senha */
      senha: string
      /**
       * Role
       * @default colaborador
       * @enum {string}
       */
      role: 'admin' | 'aprovador' | 'colaborador'
      /**
       * Nivel Aprovacao
       * @default 0
       */
      nivel_aprovacao: number
    }
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Nome */
      nome: string
      /** Email */
      email: string
      /**
       * Role
       * @enum {string}
       */
      role: 'admin' | 'aprovador' | 'colaborador'
      /** Nivel Aprovacao */
      nivel_aprovacao: number
      /** Ativo */
      ativo: boolean
      /** Ultimo Login Em */
      ultimo_login_em: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** UserUpdate */
    UserUpdate: {
      /** Nome */
      nome?: string | null
      /** Role */
      role?: ('admin' | 'aprovador' | 'colaborador') | null
      /** Nivel Aprovacao */
      nivel_aprovacao?: number | null
      /** Ativo */
      ativo?: boolean | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthReport']
        }
      }
      /** @description Algum componente indisponível */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthReport']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        refresh_token?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        refresh_token?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_v1_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Me']
        }
      }
    }
  }
  list_users_api_v1_users_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut'][]
        }
      }
    }
  }
  create_user_api_v1_users_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  buscar_api_v1_suppliers_get: {
    parameters: {
      query?: {
        /** @description Nome ou início do CNPJ */
        q?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_suppliers_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SupplierIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  obter_api_v1_suppliers__supplier_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        supplier_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  excluir_api_v1_suppliers__supplier_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        supplier_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_suppliers__supplier_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        supplier_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SupplierUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  listar_api_v1_categorias_get: {
    parameters: {
      query?: {
        /** @description Inclui registros desativados */
        incluir_inativos?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoriaOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_categorias_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoriaIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoriaOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_categorias__obj_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        obj_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoriaUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoriaOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  listar_api_v1_projetos_get: {
    parameters: {
      query?: {
        /** @description Inclui registros desativados */
        incluir_inativos?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjetoOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_projetos_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjetoIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjetoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_projetos__obj_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        obj_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjetoUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjetoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  listar_api_v1_centros_custo_get: {
    parameters: {
      query?: {
        /** @description Inclui registros desativados */
        incluir_inativos?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CentroCustoOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_centros_custo_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CentroCustoIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CentroCustoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_centros_custo__obj_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        obj_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CentroCustoUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CentroCustoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  listar_api_v1_tags_get: {
    parameters: {
      query?: {
        /** @description Inclui registros desativados */
        incluir_inativos?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_tags_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TagIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_tags__obj_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        obj_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TagUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  listar_api_v1_lancamentos_get: {
    parameters: {
      query?: {
        /** @description Status efetivo (repita para vários) */
        status?: components['schemas']['StatusEfetivo'][] | null
        supplier_id?: string | null
        categoria_id?: string | null
        projeto_id?: string | null
        centro_custo_id?: string | null
        /** @description Tag (repita para exigir várias ao mesmo tempo) */
        tag_id?: string[] | null
        vencimento_de?: string | null
        vencimento_ate?: string | null
        limit?: number
        cursor?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LancamentoPage']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_api_v1_lancamentos_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LancamentoIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LancamentoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  obter_api_v1_lancamentos__lanc_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        lanc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LancamentoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  excluir_api_v1_lancamentos__lanc_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        lanc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  atualizar_api_v1_lancamentos__lanc_id__patch: {
    parameters: {
      query?: never
      header?: {
        /** @description Versão esperada, ex.: "3" */
        'if-match'?: string | null
      }
      path: {
        lanc_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LancamentoUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LancamentoOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  criar_lote_api_v1_uploads_batch_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NovoLote']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoteCriado']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirmar_api_v1_uploads__comprovante_id__complete_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        comprovante_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Confirmacao']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  nova_url_api_v1_uploads__comprovante_id__retry_url_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        comprovante_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadInstrucao']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  status_lote_api_v1_uploads_batch__batch_id__status_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        batch_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoteStatus']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  baixar_arquivo_api_v1_comprovantes__comprovante_id__arquivo_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        comprovante_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  miniatura_api_v1_comprovantes__comprovante_id__thumbnail_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        comprovante_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
